version: '3'
services:
  backend:
    container_name: teleport-python
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    volumes:
      - .:/app
    env_file: .env
    stdin_open: true
    tty: true
